/* ---- Feste Auswahllisten: Klasse und Gruppe ----
   Hier aendern, wenn eine Klasse oder eine Gruppe dazukommt. Beide Apps lesen daraus. */
const KLASSEN = ["HFD", "HFE1", "HFE2"];
const GRUPPEN = ["Gruppe 1", "Gruppe 2", "Team 1", "Team 2"];

/* ---- Kriterien Servicepraxis ---- */
const CRITS = [
  {k:"gas", de:"Gastgeberhaltung und Gästekontakt", en:"Host attitude and guest contact", th:"ความเป็นเจ้าบ้านและการดูแลแขก", zh:"待客态度与客人接触", s:{de:"Gastgeber",en:"Host",th:"เจ้าบ้าน",zh:"待客"}},
  {k:"hyg", de:"Hygiene und Erscheinungsbild", en:"Hygiene and grooming", th:"สุขอนามัยและบุคลิกภาพ", zh:"卫生与仪容", s:{de:"Hygiene",en:"Hygiene",th:"สุขอนามัย",zh:"卫生"}},
  {k:"mep", de:"Mise en Place und Organisation", en:"Mise en place and organisation", th:"มีซ็องปลัสและการจัดระบบงาน", zh:"准备工作与组织", s:{de:"Mise en Place",en:"Mise en place",th:"มีซ็องปลัส",zh:"准备工作"}},
  {k:"tec", de:"Arbeitstechnik Service", en:"Service technique", th:"เทคนิคการบริการ", zh:"服务技术", s:{de:"Technik",en:"Technique",th:"เทคนิค",zh:"服务技术"}},
  {k:"ver", de:"Verkauf und Beratung", en:"Sales and advice", th:"การขายและการแนะนำ", zh:"销售与顾问式推荐", s:{de:"Verkauf",en:"Sales",th:"การขาย",zh:"销售"}},
  {k:"tea", de:"Teamfähigkeit", en:"Teamwork", th:"การทำงานเป็นทีม", zh:"团队合作", s:{de:"Team",en:"Team",th:"ทีม",zh:"团队"}},
  {k:"sel", de:"Selbständigkeit", en:"Independence", th:"การทำงานด้วยตนเอง", zh:"自主性", s:{de:"Selbständig",en:"Independence",th:"พึ่งตนเอง",zh:"自主性"}},
  {k:"mot", de:"Motivation", en:"Motivation", th:"แรงจูงใจ", zh:"工作态度", s:{de:"Motivation",en:"Motivation",th:"แรงจูงใจ",zh:"工作态度"}},
  {k:"auf", de:"Aufmerksamkeit und Effizienz", en:"Awareness and efficiency", th:"ความใส่ใจและประสิทธิภาพ", zh:"洞察力与效率", s:{de:"Aufmerksamkeit",en:"Awareness",th:"ความใส่ใจ",zh:"洞察力"}}
];

/* ---- Bausteinbibliothek: i=id c=Kriterium d=Richtung w=Gewicht t=Text a=Massnahme ---- */
const CHIPS = [
/* GASTGEBERHALTUNG UND GAESTEKONTAKT */
{i:"gas-p1",c:"gas",d:1,w:W.m,t:{de:"Gast beim Eintreten sofort mit Blickkontakt begrüsst und empfangen",en:"Greeted and welcomed the guest immediately with eye contact",th:"ทักทายและต้อนรับแขกทันทีพร้อมสบตา",zh:"客人进门即以目光接触问候并迎接"}},
{i:"gas-p3",c:"gas",d:1,w:W.m,t:{de:"Reklamation ruhig aufgenommen, Verständnis gezeigt und eine Lösung angeboten",en:"Handled a complaint calmly, showed understanding and offered a solution",th:"รับข้อร้องเรียนอย่างใจเย็น แสดงความเข้าใจ และเสนอทางแก้ไข",zh:"冷静受理投诉，表示理解并提出解决方案"}},
{i:"gas-p4",c:"gas",d:1,w:W.m,t:{de:"Präsenz im Revier gehalten, aufmerksam und ohne aufdringlich zu wirken",en:"Maintained presence in the station, attentive without being intrusive",th:"อยู่ประจำโซนอย่างสม่ำเสมอ ใส่ใจแต่ไม่รบกวนแขก",zh:"始终在责任区内保持存在感，关注而不打扰"}},
{i:"gas-p5",c:"gas",d:1,w:W.s,t:{de:"Heikle Gastsituation souverän entschärft, Gast verliess das Lokal zufrieden",en:"Defused a difficult guest situation confidently, the guest left satisfied",th:"คลี่คลายสถานการณ์ยากกับแขกได้อย่างมืออาชีพ แขกกลับไปอย่างพอใจ",zh:"从容化解棘手的客人状况，客人满意离店"}},
{i:"gas-n1",c:"gas",d:-1,w:W.m,t:{de:"Gast beim Eintreten nicht beachtet, Begrüssung verzögert",en:"Guest not noticed on arrival, greeting delayed",th:"ไม่สังเกตเห็นแขกเมื่อเข้ามา ทักทายล่าช้า",zh:"客人进门未被注意，问候延迟"},a:{de:"Vereinbart im Team ein festes Blickfeld zur Türe und begrüsst jeden Gast innerhalb von 30 Sekunden, auch wenn ihr noch am Arbeiten seid.",en:"Agree in the team who keeps an eye on the door and greet every guest within 30 seconds, even while working.",th:"ตกลงกันในทีมว่าใครคอยมองประตู และทักทายแขกทุกคนภายใน 30 วินาที แม้กำลังทำงานอยู่",zh:"在团队内约定由谁留意门口，并在 30 秒内问候每位客人，即使手头仍有工作。"}},
{i:"gas-n3",c:"gas",d:-1,w:W.m,t:{de:"Reklamation abgewiesen oder an den Gast zurückgegeben, ohne Lösung anzubieten",en:"Complaint rejected or pushed back to the guest without offering a solution",th:"ปฏิเสธข้อร้องเรียนหรือโยนกลับให้แขก โดยไม่เสนอทางแก้ไข",zh:"拒绝投诉或把问题推回给客人，未提出解决方案"},a:{de:"Nutze die Schrittfolge zuhören, danken, Verständnis zeigen, Lösung anbieten, Vorgesetzte informieren.",en:"Use the sequence: listen, thank, show understanding, offer a solution, inform your supervisor.",th:"ใช้ลำดับขั้น: ฟัง ขอบคุณ แสดงความเข้าใจ เสนอทางแก้ และแจ้งหัวหน้า",zh:"按顺序处理：倾听、致谢、表示理解、提出方案、告知上级。"}},
{i:"gas-n5",c:"gas",d:-1,w:W.m,t:{de:"Revier längere Zeit verlassen, Gäste ohne Ansprechperson",en:"Left the station for a longer period, guests without a contact person",th:"ออกจากโซนรับผิดชอบเป็นเวลานาน แขกไม่มีผู้ดูแล",zh:"长时间离开责任区，客人无人照应"},a:{de:"Sprich dich mit deinem Partner ab, wer das Revier übernimmt, bevor du es verlässt.",en:"Agree with your partner who covers the station before you leave it.",th:"ตกลงกับคู่งานว่าใครดูแลโซนแทน ก่อนที่คุณจะออกไป",zh:"离开责任区前，先与搭档约定由谁接手。"}},
{i:"gas-n7",c:"gas",d:-1,w:W.s,t:{de:"Gast sichtbar verärgert zurückgelassen, keine Weitergabe an die Vorgesetzten",en:"Guest left visibly annoyed, situation not passed on to a supervisor",th:"ปล่อยให้แขกไม่พอใจอย่างเห็นได้ชัด และไม่แจ้งหัวหน้า",zh:"让客人明显带着不满离开，且未向上级反映"},a:{de:"Informiere bei jeder unklaren Gastsituation sofort die Serviceleitung, damit sie noch im Haus gelöst werden kann.",en:"Inform the service manager immediately about any unresolved guest situation so it can be settled while the guest is still in the house.",th:"แจ้งหัวหน้าแผนกบริการทันทีเมื่อมีสถานการณ์ที่ยังไม่คลี่คลาย เพื่อแก้ไขขณะแขกยังอยู่ในร้าน",zh:"遇到未解决的客人状况立即告知服务主管，以便客人仍在店内时处理。"}},
{i:"gas-ko",c:"gas",d:-1,w:0,ko:true,t:{de:"Respektloses Verhalten gegenüber Gast oder Team (Gastgeberhaltung = 1.0)",en:"Disrespectful behaviour towards a guest or the team (Host attitude = 1.0)",th:"พฤติกรรมไม่ให้เกียรติแขกหรือเพื่อนร่วมทีม (ความเป็นเจ้าบ้าน = 1.0)",zh:"对客人或同事表现出不尊重（待客态度记 1.00）"},a:{de:"Besprich schwierige Situationen ausserhalb des Gastbereichs mit der Serviceleitung; im Gastraum gilt immer Zurückhaltung.",en:"Discuss difficult situations with the service manager away from the guest area; in the restaurant always stay restrained.",th:"พูดคุยเรื่องยากกับหัวหน้าแผนกนอกพื้นที่บริการ ในห้องอาหารต้องสำรวมเสมอ",zh:"把棘手情况带到客区之外与服务主管讨论；在餐厅内始终保持克制。"}},

/* HYGIENE UND ERSCHEINUNGSBILD */
{i:"hyg-p1",c:"hyg",d:1,w:W.m,t:{de:"Uniform vollständig, sauber und gebügelt",en:"Uniform complete, clean and pressed",th:"ชุดยูนิฟอร์มครบถ้วน สะอาด และรีดเรียบ",zh:"制服完整、干净、熨烫平整"}},
{i:"hyg-p3",c:"hyg",d:1,w:W.m,t:{de:"Händehygiene korrekt und an den richtigen Stellen eingehalten",en:"Hand hygiene applied correctly and at the right moments",th:"ปฏิบัติสุขอนามัยมือถูกต้องและถูกจังหวะ",zh:"在正确的环节正确执行手部卫生"}},
{i:"hyg-p4",c:"hyg",d:1,w:W.m,t:{de:"Gläser am Stiel und Besteck am Griff angefasst",en:"Held glasses by the stem and cutlery by the handle",th:"จับแก้วที่ก้านและจับช้อนส้อมที่ด้าม",zh:"握持酒杯持杯脚、餐具持柄"}},
{i:"hyg-p5",c:"hyg",d:1,w:W.l,t:{de:"Station und Office während des Service sauber gehalten",en:"Kept station and back office clean throughout service",th:"รักษาความสะอาดของสเตชันและห้องเตรียมตลอดการบริการ",zh:"服务期间保持工作台与备餐间整洁"}},
{i:"hyg-n1",c:"hyg",d:-1,w:W.m,t:{de:"Uniform unvollständig oder verschmutzt",en:"Uniform incomplete or soiled",th:"ชุดยูนิฟอร์มไม่ครบหรือไม่สะอาด",zh:"制服不完整或不整洁"},a:{de:"Kontrolliere vor Dienstbeginn Hemd, Hose, Schuhe, Gilet und Foulard und halte eine Ersatzgarnitur im Spind bereit.",en:"Check shirt, trousers, shoes, waistcoat and neckerchief before the shift and keep a spare set in your locker.",th:"ตรวจเสื้อ กางเกง รองเท้า เสื้อกั๊ก และผ้าพันคอก่อนเข้างาน และเก็บชุดสำรองไว้ในล็อกเกอร์",zh:"上岗前检查衬衫、长裤、鞋、马甲和领巾，并在更衣柜备一套替换。"}},
{i:"hyg-n3",c:"hyg",d:-1,w:W.m,t:{de:"Gläser am Kelch oder Besteck an der Lauffläche angefasst",en:"Held glasses by the bowl or cutlery by the blade or tines",th:"จับแก้วที่ตัวแก้ว หรือจับช้อนส้อมที่ส่วนใช้งาน",zh:"握持杯身或触碰餐具的进食部位"},a:{de:"Trag Gläser konsequent am Stiel oder auf dem Tablett und nimm Besteck nur am Griff.",en:"Always carry glasses by the stem or on a tray and pick up cutlery only by the handle.",th:"ถือแก้วที่ก้านหรือใช้ถาดเสมอ และหยิบช้อนส้อมที่ด้ามเท่านั้น",zh:"始终持杯脚或用托盘搬运酒杯，餐具只握柄部。"}},
{i:"hyg-n4",c:"hyg",d:-1,w:W.m,t:{de:"Händehygiene nach kritischem Arbeitsschritt unterlassen",en:"Hand hygiene omitted after a critical step",th:"ไม่ล้างมือหลังขั้นตอนที่มีความเสี่ยง",zh:"关键环节后未执行手部卫生"},a:{de:"Wasch die Hände nach jedem Abräumen, vor dem Anfassen von sauberem Material und nach jeder Pause.",en:"Wash your hands after every clearing round, before handling clean items and after every break.",th:"ล้างมือทุกครั้งหลังเก็บจาน ก่อนหยิบของสะอาด และหลังพักทุกครั้ง",zh:"每次收台后、接触洁净物品前以及每次休息后都要洗手。"}},
{i:"hyg-n6",c:"hyg",d:-1,w:W.s,t:{de:"Verschmutztes oder beschädigtes Material an den Gast gegeben",en:"Soiled or damaged item given to the guest",th:"ส่งภาชนะที่สกปรกหรือชำรุดให้แขก",zh:"把有污渍或破损的器皿给了客人"},a:{de:"Kontrollier Glas, Teller und Besteck im Gegenlicht, bevor du eindeckst oder servierst.",en:"Check glasses, plates and cutlery against the light before laying up or serving.",th:"ตรวจแก้ว จาน และช้อนส้อมโดยส่องกับแสงก่อนจัดโต๊ะหรือเสิร์ฟ",zh:"摆台或上菜前对光检查玻璃杯、餐盘和餐具。"}},
{i:"hyg-ko",c:"hyg",d:-1,w:0,ko:true,t:{de:"Grober Hygiene- oder HACCP-Verstoss (Hygiene = 1.0)",en:"Serious hygiene or HACCP breach (Hygiene = 1.0)",th:"ละเมิดสุขอนามัยหรือ HACCP อย่างร้ายแรง (สุขอนามัย = 1.0)",zh:"严重违反卫生或 HACCP 规定（卫生记 1.00）"},a:{de:"Hol bei jeder Unsicherheit zu Temperatur, Haltbarkeit oder Allergenen vor dem Servieren die Bestätigung der Fachlehrperson.",en:"Whenever you are unsure about temperature, shelf life or allergens, get confirmation from the lecturer before serving.",th:"เมื่อไม่แน่ใจเรื่องอุณหภูมิ อายุการเก็บ หรือสารก่อภูมิแพ้ ให้ขอการยืนยันจากอาจารย์ก่อนเสิร์ฟ",zh:"对温度、保质期或过敏原有任何不确定时，上菜前先向授课教师确认。"}},
{i:"hyg-ko2",c:"hyg",d:-1,w:0,ko:true,t:{de:"Wiederholter vermeidbarer Uniform- oder Erscheinungsbildverstoss (Hygiene = 1.0)",en:"Repeated avoidable breach of uniform or grooming rules (Hygiene = 1.0)",th:"ละเมิดระเบียบชุดหรือบุคลิกภาพซ้ำโดยหลีกเลี่ยงได้ (สุขอนามัย = 1.0)",zh:"重复出现本可避免的制服或仪容违规（卫生记 1.00）"},a:{de:"Notier den Hinweis und kontrollier den betroffenen Punkt am Folgetag aktiv vor dem Briefing.",en:"Write the feedback down and actively check that point before the next day's briefing.",th:"จดคำแนะนำไว้ และตรวจจุดนั้นก่อนบรีฟในวันถัดไป",zh:"把提醒记下来，第二天简报前主动检查该项。"}},

/* MISE EN PLACE UND ORGANISATION */
{i:"mep-p1",c:"mep",d:1,w:W.m,t:{de:"Station vor Serviceanfang vollständig vorbereitet und kontrolliert",en:"Station fully prepared and checked before service",th:"เตรียมสเตชันครบถ้วนและตรวจสอบก่อนเริ่มบริการ",zh:"服务开始前工作台准备完整并已检查"}},
{i:"mep-p2",c:"mep",d:1,w:W.m,t:{de:"Eingedeckt exakt nach Standard (Abstände, Ausrichtung, Symmetrie)",en:"Laid up exactly to standard (spacing, alignment, symmetry)",th:"จัดโต๊ะตรงตามมาตรฐาน (ระยะ แนว ความสมมาตร)",zh:"严格按标准摆台（间距、对齐、对称）"}},
{i:"mep-p3",c:"mep",d:1,w:W.l,t:{de:"Nachschub selbständig ergänzt, bevor etwas ausging",en:"Replenished supplies independently before anything ran out",th:"เติมของใช้ด้วยตนเองก่อนของจะหมด",zh:"在物品用尽前主动补充"}},
{i:"mep-p4",c:"mep",d:1,w:W.m,t:{de:"Abschlussarbeiten vollständig und fristgerecht erledigt",en:"Closing duties completed fully and on time",th:"ทำงานปิดร้านครบถ้วนและตรงเวลา",zh:"收尾工作完整且按时完成"}},
{i:"mep-n1",c:"mep",d:-1,w:W.m,t:{de:"Mise en Place bei Serviceanfang unvollständig",en:"Mise en place incomplete at the start of service",th:"มีซ็องปลัสไม่ครบเมื่อเริ่มบริการ",zh:"开餐时准备工作不完整"},a:{de:"Arbeite mit einer festen Checkliste für deine Station und hak sie 15 Minuten vor Serviceanfang ab.",en:"Use a fixed checklist for your station and tick it off 15 minutes before service starts.",th:"ใช้เช็กลิสต์ประจำสเตชัน และตรวจให้ครบ 15 นาทีก่อนเริ่มบริการ",zh:"为你的工作台制定固定检查表，并在开餐前 15 分钟逐项核对。"}},
{i:"mep-n2",c:"mep",d:-1,w:W.l,t:{de:"Eindecken ungenau (Abstände, Ausrichtung, Logo)",en:"Table laid inaccurately (spacing, alignment, logo)",th:"จัดโต๊ะไม่เรียบร้อย (ระยะ แนว โลโก้)",zh:"摆台不精确（间距、对齐、标志方向）"},a:{de:"Kontrollier den Tisch am Schluss aus Gastperspektive, indem du dich einmal hinsetzt.",en:"Check the finished table from the guest's perspective by sitting down once.",th:"ตรวจโต๊ะที่จัดเสร็จจากมุมมองแขก โดยลองนั่งลงสักครั้ง",zh:"摆好后坐下一次，从客人视角检查整张桌子。"}},
{i:"mep-n3",c:"mep",d:-1,w:W.m,t:{de:"Während des Service ging Material aus, kein Nachschub vorbereitet",en:"Ran out of items during service, no replenishment prepared",th:"ของหมดระหว่างบริการ ไม่ได้เตรียมของเติม",zh:"服务中物品用尽，未备补给"},a:{de:"Leg für die kritischen Artikel eine Mindestmenge fest und füll nach jedem Gang auf.",en:"Define a minimum stock for the critical items and top up after every course.",th:"กำหนดจำนวนขั้นต่ำสำหรับของสำคัญ และเติมหลังเสิร์ฟทุกคอร์ส",zh:"为关键物品设定最低存量，每道菜后补充一次。"}},
{i:"mep-n4",c:"mep",d:-1,w:W.m,t:{de:"Abschlussarbeiten unvollständig oder an andere abgegeben",en:"Closing duties incomplete or handed to others",th:"งานปิดร้านไม่ครบ หรือโยนให้ผู้อื่น",zh:"收尾工作未完成或推给他人"},a:{de:"Teilt die Abschlussarbeiten zu Beginn im Team auf und meld dich erst ab, wenn dein Teil kontrolliert ist.",en:"Divide the closing duties in the team at the start and only sign off once your part has been checked.",th:"แบ่งงานปิดร้านกันตั้งแต่ต้น และเลิกงานเมื่อส่วนของคุณถูกตรวจแล้วเท่านั้น",zh:"开工时就在团队内分配收尾任务，自己那部分经检查后才下班。"}},
{i:"mep-n7",c:"mep",d:-1,w:W.s,t:{de:"Station am Serviceende nicht betriebsbereit hinterlassen",en:"Station not left ready for operation at the end of service",th:"ไม่ส่งมอบสเตชันในสภาพพร้อมใช้งานเมื่อจบบริการ",zh:"服务结束时工作台未处于可运营状态"},a:{de:"Kontrollier am Schluss anhand der Checkliste, ob die Station für die nächste Schicht startklar ist.",en:"Use the checklist at the end to confirm the station is ready for the next shift.",th:"ใช้เช็กลิสต์ตอนจบงานเพื่อยืนยันว่าสเตชันพร้อมสำหรับกะถัดไป",zh:"结束时按检查表确认工作台已为下一班做好准备。"}},

/* ARBEITSTECHNIK SERVICE */
{i:"tec-p1",c:"tec",d:1,w:W.m,t:{de:"Tragetechnik sicher und korrekt (Teller, Tablett, Gläser)",en:"Carrying technique safe and correct (plates, tray, glasses)",th:"เทคนิคการถือปลอดภัยและถูกต้อง (จาน ถาด แก้ว)",zh:"端托技术安全规范（餐盘、托盘、酒杯）"}},
{i:"tec-p2",c:"tec",d:1,w:W.m,t:{de:"Servier- und Aushebeseite nach Hausstandard eingehalten",en:"Served and cleared from the correct side per house standard",th:"เสิร์ฟและเก็บจานตามด้านที่ถูกต้องตามมาตรฐานร้าน",zh:"按本店标准从正确一侧上菜和收台"}},
{i:"tec-p3",c:"tec",d:1,w:W.m,t:{de:"Getränkeservice fachgerecht (Glaswahl, Temperatur, Einschenkmenge, Flaschenhaltung)",en:"Beverage service professional (glass, temperature, pouring quantity, bottle handling)",th:"บริการเครื่องดื่มอย่างมืออาชีพ (เลือกแก้ว อุณหภูมิ ปริมาณริน การจับขวด)",zh:"饮品服务专业（选杯、温度、斟倒量、持瓶）"}},
{i:"tec-p4",c:"tec",d:1,w:W.s,t:{de:"Arbeit am Gast sicher ausgeführt (Tranchieren, Filetieren, Flambieren, Dekantieren)",en:"Guéridon work performed confidently (carving, filleting, flambéing, decanting)",th:"ทำงานหน้าแขกได้อย่างมั่นใจ (แล่ ตัด ฟลามเบ้ เดคานต์)",zh:"桌边操作稳健（分切、剔骨、火焰烹调、醒酒）"}},
{i:"tec-p5",c:"tec",d:1,w:W.m,t:{de:"Weinservice vollständig nach Standard (Präsentation, Degustation, Reihenfolge)",en:"Wine service complete to standard (presentation, tasting, order of service)",th:"บริการไวน์ครบตามมาตรฐาน (นำเสนอ ชิม ลำดับการเสิร์ฟ)",zh:"葡萄酒服务符合标准（示瓶、品鉴、顺序）"}},
{i:"tec-n1",c:"tec",d:-1,w:W.m,t:{de:"Unsichere Tragetechnik, Gefahr für Gast oder Material",en:"Unsafe carrying technique, risk to guests or material",th:"เทคนิคการถือไม่มั่นคง เสี่ยงต่อแขกหรือภาชนะ",zh:"端托不稳，存在伤及客人或损坏器皿的风险"},a:{de:"Üb die Tragetechnik mit leerem Geschirr ausserhalb der Servicezeit, bis der Griff sitzt.",en:"Practise carrying with empty crockery outside service hours until the grip is secure.",th:"ฝึกถือด้วยภาชนะเปล่านอกเวลาบริการจนกว่าจะจับได้มั่นคง",zh:"在非服务时段用空餐具练习，直到手法稳固。"}},
{i:"tec-n2",c:"tec",d:-1,w:W.l,t:{de:"Servier- oder Aushebeseite nicht eingehalten",en:"Served or cleared from the wrong side",th:"เสิร์ฟหรือเก็บจานผิดด้าน",zh:"上菜或收台的方位不符规定"},a:{de:"Halt dich an den Hausstandard und frag im Briefing nach, sobald du unsicher bist.",en:"Follow the house standard and ask during the briefing as soon as you are unsure.",th:"ยึดตามมาตรฐานของร้าน และถามในช่วงบรีฟทันทีที่ไม่แน่ใจ",zh:"遵循本店标准，一有不确定就在简报时提问。"}},
{i:"tec-n3",c:"tec",d:-1,w:W.m,t:{de:"Getränkeservice fehlerhaft (Glaswahl, Temperatur, Menge)",en:"Beverage service faulty (glass, temperature, quantity)",th:"บริการเครื่องดื่มผิดพลาด (แก้ว อุณหภูมิ ปริมาณ)",zh:"饮品服务有误（选杯、温度、分量）"},a:{de:"Kontrollier vor dem Ausschenken Glas, Temperatur und Menge anhand der Getränkekarte.",en:"Check glass, temperature and quantity against the drinks list before pouring.",th:"ตรวจแก้ว อุณหภูมิ และปริมาณตามรายการเครื่องดื่มก่อนริน",zh:"斟倒前对照酒水单核对杯型、温度和分量。"}},
{i:"tec-n4",c:"tec",d:-1,w:W.s,t:{de:"Arbeit am Gast abgebrochen oder misslungen, Gast musste warten",en:"Guéridon work abandoned or failed, the guest had to wait",th:"งานหน้าแขกทำไม่สำเร็จหรือต้องยกเลิก แขกต้องรอ",zh:"桌边操作中断或失败，客人被迫等待"},a:{de:"Üb die Arbeit am Gast im Trockenlauf und bereite Material und Ablauf vor dem Gang vollständig vor.",en:"Rehearse the guéridon work dry and prepare material and sequence completely before the course.",th:"ซ้อมงานหน้าแขกแบบไม่ใช้ของจริง และเตรียมอุปกรณ์กับลำดับขั้นให้ครบก่อนเสิร์ฟ",zh:"先做空练，并在上该道菜前把器具和流程准备齐全。"}},
{i:"tec-n6",c:"tec",d:-1,w:W.m,t:{de:"Weinservice unvollständig (keine Präsentation, keine Degustation, falsche Reihenfolge)",en:"Wine service incomplete (no presentation, no tasting, wrong order)",th:"บริการไวน์ไม่ครบ (ไม่นำเสนอ ไม่ให้ชิม ลำดับผิด)",zh:"葡萄酒服务不完整（未示瓶、未品鉴、顺序错误）"},a:{de:"Arbeite den Weinservice anhand der festen Schrittfolge ab und lass dir die Reihenfolge von der Fachlehrperson einmal bestätigen.",en:"Work through the fixed sequence for wine service and have the lecturer confirm the order once.",th:"ทำตามลำดับขั้นบริการไวน์ที่กำหนด และให้อาจารย์ยืนยันลำดับสักครั้ง",zh:"按固定步骤完成酒水服务，并请教师确认一次顺序。"}},

/* VERKAUF UND BERATUNG */
{i:"ver-p1",c:"ver",d:1,w:W.m,t:{de:"Menü- und Getränkekenntnisse sicher, Gastfragen kompetent beantwortet",en:"Sound knowledge of menu and drinks, answered guest questions competently",th:"รู้เมนูและเครื่องดื่มดี ตอบคำถามแขกได้อย่างมืออาชีพ",zh:"熟悉菜单与酒水，能称职回答客人提问"}},
{i:"ver-p2",c:"ver",d:1,w:W.m,t:{de:"Aktive Empfehlung ausgesprochen, passend zur Gastsituation",en:"Gave an active recommendation that matched the guest's situation",th:"แนะนำเชิงรุกได้เหมาะกับสถานการณ์ของแขก",zh:"主动给出契合客人情境的推荐"}},
{i:"ver-p3",c:"ver",d:1,w:W.m,t:{de:"Zusatzverkauf gelungen (Apéritif, Wasser, Dessert, Kaffee, Digestif)",en:"Successful upselling (aperitif, water, dessert, coffee, digestif)",th:"ขายเพิ่มได้สำเร็จ (อะเพริทีฟ น้ำ ของหวาน กาแฟ ดิเจสทีฟ)",zh:"成功完成加售（餐前酒、水、甜点、咖啡、餐后酒）"}},
{i:"ver-p4",c:"ver",d:1,w:W.m,t:{de:"Passende Weinbegleitung zum Gericht vorgeschlagen",en:"Suggested a fitting wine pairing for the dish",th:"แนะนำไวน์ที่เข้ากับอาหารได้เหมาะสม",zh:"为菜品推荐了合适的配酒"}},
{i:"ver-n1",c:"ver",d:-1,w:W.m,t:{de:"Frage zu Speisen oder Getränken nicht beantwortet und nicht abgeklärt",en:"Question about food or drinks left unanswered and not clarified",th:"ไม่ตอบคำถามเรื่องอาหารหรือเครื่องดื่ม และไม่ไปสอบถามให้ชัด",zh:"对菜品或酒水的提问未作答也未去核实"},a:{de:"Lies die Karte vor dem Service durch und notier dir drei Fragen, die du im Briefing klären willst.",en:"Read the menu before service and note three questions to clarify during the briefing.",th:"อ่านเมนูก่อนเริ่มบริการ และจดคำถามสามข้อไว้ถามในช่วงบรีฟ",zh:"开餐前通读菜单，记下三个问题在简报时澄清。"}},
{i:"ver-n2",c:"ver",d:-1,w:W.l,t:{de:"Keine Empfehlung ausgesprochen, obwohl die Situation es anbot",en:"No recommendation given although the situation invited one",th:"ไม่ได้แนะนำอะไรเลย ทั้งที่สถานการณ์เอื้อ",zh:"情境适合推荐却未开口"},a:{de:"Leg dir pro Gang eine Empfehlung zurecht und sprich sie aktiv an.",en:"Prepare one recommendation per course and offer it actively.",th:"เตรียมคำแนะนำไว้หนึ่งอย่างต่อหนึ่งคอร์ส และเสนอเชิงรุก",zh:"为每道菜准备一个推荐，并主动提出。"}},
{i:"ver-n4",c:"ver",d:-1,w:W.m,t:{de:"Falsche Angaben zu Speisen, Getränken oder Preisen gemacht",en:"Gave incorrect information on dishes, drinks or prices",th:"ให้ข้อมูลอาหาร เครื่องดื่ม หรือราคาผิด",zh:"对菜品、酒水或价格提供了错误信息"},a:{de:"Sag offen, dass du nachfragst, und hol die Information, statt zu schätzen.",en:"Say openly that you will check, and get the information instead of guessing.",th:"บอกแขกตรง ๆ ว่าจะไปตรวจสอบ แล้วไปหาข้อมูลจริง อย่าเดา",zh:"坦率告知客人你去确认，然后取得准确信息，不要靠猜。"}},
{i:"ver-n7",c:"ver",d:-1,w:W.m,t:{de:"Allergenfrage des Gastes ohne Abklärung beantwortet",en:"Answered an allergen question without checking",th:"ตอบคำถามเรื่องสารก่อภูมิแพ้โดยไม่ตรวจสอบ",zh:"未经核实就回答过敏原问题"},a:{de:"Klär jede Allergenfrage in der Küche ab und gib die Antwort erst danach weiter.",en:"Clarify every allergen question with the kitchen and pass on the answer only afterwards.",th:"สอบถามเรื่องสารก่อภูมิแพ้กับครัวทุกครั้ง แล้วจึงแจ้งคำตอบแก่แขก",zh:"所有过敏原问题都先与厨房核实，之后再答复客人。"}},

/* TEAMFAEHIGKEIT */
{i:"tea-lt",c:"tea",d:-1,w:W.m,t:{de:"Verspätet zum Dienst erschienen",en:"Arrived late for the shift",th:"มาทำงานสาย",zh:"上班迟到"},a:{de:"Plane den Arbeitsweg mit zehn Minuten Reserve und melde eine absehbare Verspätung vorher.",en:"Plan your journey with ten minutes to spare and report a foreseeable delay in advance.",th:"เผื่อเวลาเดินทางสิบนาที และแจ้งล่วงหน้าหากคาดว่าจะมาสาย",zh:"通勤预留十分钟，可预见的迟到请提前通知。"}},
{i:"tea-p1",c:"tea",d:1,w:W.m,t:{de:"Kolleginnen und Kollegen aktiv unterstützt, ohne dazu aufgefordert zu werden",en:"Actively supported colleagues without being asked",th:"ช่วยเหลือเพื่อนร่วมงานเชิงรุกโดยไม่ต้องมีใครบอก",zh:"无需提醒主动支援同事"}},
{i:"tea-p2",c:"tea",d:1,w:W.l,t:{de:"Informationen zuverlässig weitergegeben (Bestellungen, Gastwünsche, Änderungen)",en:"Passed on information reliably (orders, guest requests, changes)",th:"ส่งต่อข้อมูลได้ครบถ้วน (ออเดอร์ ความต้องการของแขก การเปลี่ยนแปลง)",zh:"可靠地传递信息（点单、客人要求、变更）"}},
{i:"tea-p3",c:"tea",d:1,w:W.m,t:{de:"Absprache mit der Küche klar und rechtzeitig",en:"Coordination with the kitchen clear and timely",th:"ประสานงานกับครัวชัดเจนและทันเวลา",zh:"与厨房沟通清晰且及时"}},
{i:"tea-p5",c:"tea",d:1,w:W.m,t:{de:"In hektischen Phasen ruhig und ausgleichend gewirkt",en:"Stayed calm and steadying during busy phases",th:"ช่วยให้ทีมสงบและสมดุลในช่วงเร่งด่วน",zh:"在繁忙时段保持冷静并稳定团队"}},
{i:"tea-n1",c:"tea",d:-1,w:W.m,t:{de:"Nur die eigene Station betreut, Kollegen im Stress stehen gelassen",en:"Looked after own station only, left colleagues under pressure",th:"ดูแลแต่สเตชันของตัวเอง ปล่อยเพื่อนร่วมงานรับภาระ",zh:"只顾自己的区域，任由同事忙不过来"},a:{de:"Schau nach jedem Gang kurz ins Nachbarrevier und biete konkret Hilfe an.",en:"Glance into the neighbouring station after every course and offer concrete help.",th:"หลังเสิร์ฟแต่ละคอร์ส ให้มองไปที่โซนข้างเคียงและเสนอความช่วยเหลือที่ชัดเจน",zh:"每道菜后看一眼邻区，并提出具体的帮忙。"}},
{i:"tea-n2",c:"tea",d:-1,w:W.m,t:{de:"Wichtige Information nicht weitergegeben (Gastwunsch, Änderung, Reklamation)",en:"Important information not passed on (guest request, change, complaint)",th:"ไม่ส่งต่อข้อมูลสำคัญ (ความต้องการของแขก การเปลี่ยนแปลง ข้อร้องเรียน)",zh:"未传递重要信息（客人要求、变更、投诉）"},a:{de:"Gib jede Information sofort weiter und lass sie dir kurz bestätigen.",en:"Pass on every piece of information immediately and have it confirmed briefly.",th:"ส่งต่อข้อมูลทุกอย่างทันที และขอการยืนยันสั้น ๆ",zh:"任何信息都立即传递，并请对方简短确认。"}},
{i:"tea-n4",c:"tea",d:-1,w:W.m,t:{de:"Kritik abgewehrt oder ignoriert",en:"Rejected or ignored feedback",th:"ปฏิเสธหรือเพิกเฉยต่อคำติชม",zh:"抗拒或无视批评意见"},a:{de:"Nimm den Hinweis zuerst entgegen, wiederhol ihn in eigenen Worten und setz ihn im nächsten Gang um.",en:"Accept the feedback first, repeat it in your own words and apply it in the next course.",th:"รับฟังก่อน ทวนด้วยคำพูดของตัวเอง แล้วนำไปใช้ในคอร์สถัดไป",zh:"先接受意见，用自己的话复述一遍，并在下一道菜中落实。"}},
{i:"tea-n5",c:"tea",d:-1,w:W.m,t:{de:"Konflikt im Team im Gastbereich ausgetragen",en:"Team conflict carried out in the guest area",th:"ทะเลาะกันในทีมต่อหน้าแขก",zh:"在客区内发生团队冲突"},a:{de:"Verschieb Klärungen ins Office und bitte die Serviceleitung um Unterstützung.",en:"Move disagreements to the back office and ask the service manager for support.",th:"ย้ายการพูดคุยไปที่ห้องหลังร้าน และขอความช่วยเหลือจากหัวหน้าแผนก",zh:"把争议移到后场处理，并请服务主管协助。"}},

/* SELBSTAENDIGKEIT */
{i:"sel-p1",c:"sel",d:1,w:W.m,t:{de:"Aufgaben selbständig erkannt und übernommen, ohne Anweisung",en:"Identified and took on tasks independently, without instruction",th:"มองเห็นงานและลงมือทำเองโดยไม่ต้องสั่ง",zh:"无需指示即发现并承担任务"}},
{i:"sel-p2",c:"sel",d:1,w:W.m,t:{de:"Im Rahmen der Kompetenz eigenständig entschieden und richtig gelegen",en:"Decided independently within their remit and got it right",th:"ตัดสินใจเองภายในขอบเขตหน้าที่ และตัดสินใจถูก",zh:"在职权范围内自主决策且判断正确"}},
{i:"sel-p3",c:"sel",d:1,w:W.l,t:{de:"Bei Unsicherheit gezielt nachgefragt, statt zu raten",en:"Asked specific questions when unsure instead of guessing",th:"เมื่อไม่แน่ใจก็ถามอย่างตรงประเด็นแทนการเดา",zh:"不确定时具体提问，而非凭猜"}},
{i:"sel-p4",c:"sel",d:1,w:W.m,t:{de:"Eigenen Fehler selbst erkannt, gemeldet und korrigiert",en:"Recognised, reported and corrected their own mistake",th:"รู้ตัวว่าทำผิด แจ้ง และแก้ไขด้วยตนเอง",zh:"自行发现、上报并纠正了自己的错误"}},
{i:"sel-n1",c:"sel",d:-1,w:W.m,t:{de:"Auf Anweisung gewartet, obwohl die Arbeit offensichtlich war",en:"Waited for instructions although the work was obvious",th:"รอคำสั่งทั้งที่งานเห็นได้ชัด",zh:"工作显而易见却仍等待指示"},a:{de:"Leg dir für Leerläufe drei Standardaufgaben zurecht, die du ohne Rückfrage übernehmen kannst.",en:"Define three standard tasks you can take on without asking whenever there is a lull.",th:"กำหนดงานมาตรฐานสามอย่างที่ทำได้เองเมื่อว่าง โดยไม่ต้องถาม",zh:"为空档期准备三项无需请示即可承担的常规任务。"}},
{i:"sel-n2",c:"sel",d:-1,w:W.m,t:{de:"Dieselbe Anweisung mehrfach gebraucht",en:"Needed the same instruction repeatedly",th:"ต้องได้รับคำสั่งเดิมซ้ำหลายครั้ง",zh:"同一指令需反复交代"},a:{de:"Notier dir Anweisungen sofort und kontrollier am Ende der Schicht, was du davon umgesetzt hast.",en:"Write instructions down immediately and check at the end of the shift what you have applied.",th:"จดคำสั่งทันที และตรวจดูตอนจบกะว่าทำไปแล้วเท่าไร",zh:"立即记下指令，下班前检查自己落实了哪些。"}},
{i:"sel-n3",c:"sel",d:-1,w:W.l,t:{de:"Bei Unsicherheit geraten, statt nachzufragen",en:"Guessed when unsure instead of asking",th:"เดาเมื่อไม่แน่ใจแทนที่จะถาม",zh:"不确定时靠猜而不提问"},a:{de:"Frag lieber einmal zu viel nach: eine Rückfrage kostet Sekunden, ein Fehler am Gast kostet den Gang.",en:"Better to ask once too often: a question costs seconds, a mistake at the table costs the whole course.",th:"ถามเกินไว้ดีกว่า: คำถามใช้เวลาไม่กี่วินาที แต่ความผิดพลาดต่อหน้าแขกเสียทั้งคอร์ส",zh:"宁可多问一次：提问只需几秒，失误却要赔上整道菜。"}},
{i:"sel-n4",c:"sel",d:-1,w:W.m,t:{de:"Eigenen Fehler nicht gemeldet",en:"Did not report their own mistake",th:"ไม่แจ้งความผิดพลาดของตนเอง",zh:"未主动上报自己的失误"},a:{de:"Meld Fehler sofort selbst, damit sie behoben sind, bevor der Gast sie bemerkt.",en:"Report mistakes yourself straight away so they can be fixed before the guest notices.",th:"แจ้งความผิดพลาดด้วยตนเองทันที เพื่อแก้ไขก่อนที่แขกจะสังเกตเห็น",zh:"失误立即自行上报，以便在客人察觉前补救。"}},

/* MOTIVATION */
{i:"mot-p1",c:"mot",d:1,w:W.m,t:{de:"Über die ganze Schicht aktiv mitgearbeitet und Einsatz gezeigt",en:"Worked actively and showed commitment throughout the shift",th:"ทำงานอย่างกระตือรือร้นและทุ่มเทตลอดกะ",zh:"整个班次积极投入、表现出干劲"}},
{i:"mot-p2",c:"mot",d:1,w:W.l,t:{de:"Von sich aus gefragt, was zu tun ist",en:"Asked of their own accord what needed doing",th:"ถามเองว่ามีอะไรให้ทำบ้าง",zh:"主动询问还有什么需要做"}},
{i:"mot-p3",c:"mot",d:1,w:W.m,t:{de:"Fachliches Interesse gezeigt, Fragen zum Fach gestellt",en:"Showed professional interest, asked technical questions",th:"แสดงความสนใจในวิชาชีพ ตั้งคำถามเชิงเทคนิค",zh:"表现出专业兴趣，提出业务问题"}},
{i:"mot-p5",c:"mot",d:1,w:W.m,t:{de:"Zusätzliche Aufgaben freiwillig übernommen",en:"Volunteered for additional tasks",th:"อาสารับงานเพิ่มเติม",zh:"自愿承担额外任务"}},
{i:"mot-n1",c:"mot",d:-1,w:W.m,t:{de:"Privates Handy im Arbeitsbereich benutzt",en:"Used a private mobile phone in the work area",th:"ใช้โทรศัพท์ส่วนตัวในพื้นที่ทำงาน",zh:"在工作区使用私人手机"},a:{de:"Lass das Handy während der Schicht im Spind; für Notfälle ist die Serviceleitung erreichbar.",en:"Leave your phone in the locker during the shift; the service manager is reachable for emergencies.",th:"เก็บโทรศัพท์ไว้ในล็อกเกอร์ระหว่างกะ กรณีฉุกเฉินติดต่อผ่านหัวหน้าแผนกได้",zh:"当班时把手机放在更衣柜；紧急情况可通过服务主管联系。"}},
{i:"mot-n2",c:"mot",d:-1,w:W.m,t:{de:"Sich der Arbeit entzogen (Rückzug ins Office, verlängerte Pausen)",en:"Avoided work (retreating to the back office, extended breaks)",th:"หลีกเลี่ยงงาน (หลบไปหลังร้าน พักนานเกิน)",zh:"回避工作（躲进后场、延长休息）"},a:{de:"Meld dich ab, wenn du den Gastbereich verlässt, und nenn Grund und Dauer.",en:"Sign off when you leave the guest area and state the reason and how long you will be.",th:"แจ้งทุกครั้งที่ออกจากพื้นที่บริการ พร้อมบอกเหตุผลและระยะเวลา",zh:"离开客区时先报备，并说明原因和时长。"}},
{i:"mot-n3",c:"mot",d:-1,w:W.l,t:{de:"Anderen zugesehen, statt mitzuarbeiten",en:"Watched others instead of joining in",th:"ยืนดูคนอื่นทำงานแทนที่จะลงมือช่วย",zh:"旁观他人而非动手参与"},a:{de:"Schliess dich bei Unsicherheit einer laufenden Arbeit an, statt zu beobachten.",en:"When unsure, join an ongoing task rather than watching.",th:"เมื่อไม่แน่ใจ ให้เข้าไปช่วยงานที่กำลังทำอยู่ แทนการยืนดู",zh:"不确定时加入正在进行的工作，而不是站着看。"}},
{i:"mot-n5",c:"mot",d:-1,w:W.m,t:{de:"Desinteresse oder Gleichgültigkeit gegenüber den Aufgaben gezeigt",en:"Showed disinterest or indifference towards the tasks",th:"แสดงความไม่สนใจหรือเฉยเมยต่องาน",zh:"对任务表现出缺乏兴趣或无所谓"},a:{de:"Such dir pro Schicht eine Aufgabe, die dich fachlich interessiert, und vertief sie.",en:"Pick one task per shift that interests you professionally and go deeper into it.",th:"เลือกงานหนึ่งอย่างต่อกะที่คุณสนใจเชิงวิชาชีพ และลงลึกกับงานนั้น",zh:"每班挑一项你专业上感兴趣的工作，把它做深。"}},

/* AUFMERKSAMKEIT UND EFFIZIENZ */
{i:"auf-p1",c:"auf",d:1,w:W.m,t:{de:"Gastsignale früh erkannt (leeres Glas, Blickkontakt, fertiger Teller)",en:"Spotted guest signals early (empty glass, eye contact, finished plate)",th:"สังเกตสัญญาณจากแขกได้เร็ว (แก้วหมด สบตา จานว่าง)",zh:"及早捕捉客人信号（空杯、目光、吃完的盘子）"}},
{i:"auf-p2",c:"auf",d:1,w:W.m,t:{de:"Revier laufend im Blick behalten, Timing der Gänge stimmte",en:"Kept the station in view throughout, course timing was right",th:"ดูแลโซนอย่างต่อเนื่อง จังหวะการเสิร์ฟแต่ละคอร์สเหมาะสม",zh:"持续关注责任区，上菜节奏把握得当"}},
{i:"auf-p3",c:"auf",d:1,w:W.m,t:{de:"Wege gebündelt, nie mit leeren Händen gelaufen",en:"Combined trips, never walked with empty hands",th:"รวบเส้นทางเดิน ไม่เดินมือเปล่า",zh:"合并动线，从不空手走动"}},
{i:"auf-p5",c:"auf",d:1,w:W.m,t:{de:"Engpass früh erkannt und selbst entschärft",en:"Recognised a bottleneck early and resolved it independently",th:"มองเห็นจุดคอขวดได้เร็วและแก้ไขด้วยตนเอง",zh:"及早发现瓶颈并自行化解"}},
{i:"auf-n1",c:"auf",d:-1,w:W.m,t:{de:"Gastsignale übersehen, Gast musste winken",en:"Missed guest signals, the guest had to wave",th:"มองข้ามสัญญาณจากแขก จนแขกต้องโบกมือเรียก",zh:"忽略客人信号，客人不得不招手"},a:{de:"Geh alle fünf Minuten bewusst einmal durch dein Revier und schau jeden Tisch an.",en:"Walk through your station deliberately every five minutes and look at every table.",th:"เดินตรวจโซนของคุณทุกห้านาที และมองทุกโต๊ะ",zh:"每五分钟有意识地巡一次责任区，逐桌看过去。"}},
{i:"auf-n2",c:"auf",d:-1,w:W.m,t:{de:"Timing der Gänge nicht im Griff, Gast wartete unnötig",en:"Course timing not under control, the guest waited unnecessarily",th:"คุมจังหวะคอร์สไม่ได้ แขกต้องรอโดยไม่จำเป็น",zh:"上菜节奏失控，客人白等"},a:{de:"Notier die Anstosszeit pro Tisch und stimm den nächsten Gang aktiv mit der Küche ab.",en:"Note the start time for each table and coordinate the next course actively with the kitchen.",th:"จดเวลาเริ่มของแต่ละโต๊ะ และประสานคอร์สถัดไปกับครัวเชิงรุก",zh:"记录每桌的开始时间，主动与厨房协调下一道菜。"}},
{i:"auf-n3",c:"auf",d:-1,w:W.l,t:{de:"Mit leeren Händen gelaufen, Wege doppelt gemacht",en:"Walked with empty hands, made trips twice",th:"เดินมือเปล่า เดินซ้ำเส้นทางเดิม",zh:"空手走动，路线重复"},a:{de:"Nimm auf jedem Rückweg etwas mit, auch wenn es nur ein Glas ist.",en:"Take something with you on every way back, even if it is only one glass.",th:"ขากลับให้หยิบอะไรติดมือมาด้วยเสมอ แม้จะเป็นแก้วใบเดียว",zh:"每次返回都顺手带点东西，哪怕只是一只杯子。"}},
{i:"auf-n4",c:"auf",d:-1,w:W.m,t:{de:"Leerlauf, obwohl im Revier Arbeit sichtbar war",en:"Idle although work was visible in the station",th:"ยืนว่างทั้งที่มีงานให้เห็นในโซน",zh:"责任区内明显有活却闲着"},a:{de:"Nutz Wartezeiten fix für Nachschub, Polieren oder Revierkontrolle.",en:"Use waiting time reliably for restocking, polishing or checking the station.",th:"ใช้เวลาว่างไปกับการเติมของ ขัดเงาภาชนะ หรือตรวจโซน",zh:"把等待时间固定用于补货、擦拭器皿或巡查责任区。"}}
];
